enum CallEvent {
  incoming,
  connecting,
  ringing,
  connected,
  reconnected,
  reconnecting,
  callEnded,
  unhold,
  hold,
  unmute,
  mute,
  speakerOn,
  speakerOff,
  bluetoothOn,
  bluetoothOff,
  audioRouteChanged, // New event for audio route changes (e.g., BT disconnected mid-call)
  log,
  permission,
  declined,
  answer,
  missedCall,
  returningCall,
}
